import torch
import torch.nn as nn
import numpy as np

# Global normalization parameters for trajectory data (X, Y, Ally_X, Ally_Y)
COMMON_MEAN = torch.tensor([0.0, 500.0, 0.0, 500.0])
COMMON_STD = torch.tensor([1500.0, 1500.0, 1500.0, 1500.0])

class Encoder(nn.Module):
    \"\"\"
    Encoder network that maps trajectory sequences to a latent representation z.
    Uses a GRU followed by a multi-layer perceptron (MLP).
    \"\"\"
    def __init__(self, input_size, hidden_dim, n_layers, n_fcs, z_dim):
        super(Encoder, self).__init__()
        self.output_size = z_dim
        self.gru = nn.GRU(input_size, hidden_dim, num_layers=n_layers, batch_first=True)
        
        fc_layers = []
        for _ in range(n_fcs - 1):
            fc_layers.append(nn.Linear(hidden_dim, hidden_dim))
            fc_layers.append(nn.ReLU())
        fc_layers.append(nn.Linear(hidden_dim, z_dim))
        fc_layers.append(nn.ReLU())
        self.fc = nn.Sequential(*fc_layers)
        
        self.register_buffer("mean", COMMON_MEAN)
        self.register_buffer("std", COMMON_STD)

    def forward(self, x):
        # Normalize input
        x_norm = (x - self.mean) / self.std
        out, _ = self.gru(x_norm)
        # Use the last hidden state for latent mapping
        last_hidden = out[:, -1, :]
        z = self.fc(last_hidden)
        return z

class Combiner(nn.Module):
    \"\"\"
    Combiner network to merge multiple latent vectors (z) from different source domains.
    Computes a simple average across available sources.
    \"\"\"
    def __init__(self):
        super(Combiner, self).__init__()
    
    def forward(self, z_list):
        # z_list: list of tensors, each (Batch, z_dim) or (z_dim,)
        zs = torch.stack(z_list, dim=0)
        return zs.mean(dim=0)

class TargetPredictor(nn.Module):
    \"\"\"
    Task solver network that predicts future positions based on trajectory history.
    Parameters of this network are generated by a HyperNetwork.
    \"\"\"
    def __init__(self, input_size, hidden_dim, n_fcs, output_size):
        super(TargetPredictor, self).__init__()
        self.gru = nn.GRU(input_size, hidden_dim, num_layers=1, batch_first=True)
        
        fc_layers = []
        for _ in range(n_fcs - 1):
            fc_layers.append(nn.Linear(hidden_dim, hidden_dim))
            fc_layers.append(nn.ReLU())
        fc_layers.append(nn.Linear(hidden_dim, output_size))
        self.fc = nn.Sequential(*fc_layers)
        
        self.register_buffer("mean", COMMON_MEAN)
        self.register_buffer("std", COMMON_STD)

    def forward(self, x):
        # Normalize input
        x_norm = (x - self.mean) / self.std
        out, _ = self.gru(x_norm)
        out = out[:, -1, :] 
        out = self.fc(out)
        return out
    
    def normalize(self, y):
        # Normalize target coordinates (X, Y)
        return (y - self.mean[:2]) / self.std[:2]

    def denormalize(self, y_norm):
        # Denormalize predicted coordinates
        return y_norm * self.std[:2] + self.mean[:2]

class HyperNetwork(nn.Module):
    \"\"\"
    HyperNetwork that generates the weights for a TargetPredictor based on the latent z.
    \"\"\"
    def __init__(self, input_size, output_size, n_fcs=2):
        super(HyperNetwork, self).__init__()
        layers = []
        curr_in = input_size
        for _ in range(n_fcs - 1):
            next_in = 64
            layers.append(nn.Linear(curr_in, next_in))
            layers.append(nn.ReLU())
            curr_in = next_in
        layers.append(nn.Linear(curr_in, output_size))
        self.net = nn.Sequential(*layers)

    def forward(self, z):
        return self.net(z)

def init_models(n_sources, n_targets=1, input_size=4, 
                enc_hidden_dim=64, enc_n_layers=1, enc_n_fcs=4,
                z_dim=8,
                dec_n_fcs=4,
                ts_hidden_dim=64, ts_nfcs=4, output_size=2,
                device=torch.device(\"cpu\")):
    \"\"\"
    Initialize all model components: encoders, combiner, decoders (hypernetworks), and the target predictor.
    \"\"\"
    # Individual encoders for each source domain
    encs = nn.ModuleList([Encoder(input_size, enc_hidden_dim, enc_n_layers, enc_n_fcs, z_dim) for _ in range(n_sources)]).to(device)
    
    # Combiner to merge multiple source latents
    combiner = Combiner().to(device)
    
    # Target Predictor structure (weights will be assigned dynamically)
    target_net = TargetPredictor(input_size, ts_hidden_dim, ts_nfcs, output_size).to(device)
    
    # Calculate total number of parameters to be generated by the HyperNetwork
    n_params = sum(p.numel() for p in target_net.parameters())
    
    # Individual decoders (HyperNetworks) for each target domain
    decs = nn.ModuleList([HyperNetwork(z_dim, n_params, dec_n_fcs) for _ in range(n_targets)]).to(device)

    return encs, combiner, decs, target_net

def put_w2net(target_net, w):
    \"\"\"
    Inject weights generated by the HyperNetwork into the TargetPredictor.
    \"\"\"
    params = {}
    offset = 0
    for name, param in target_net.named_parameters():
        size = param.numel()
        params[name] = w[offset : offset + size].view(param.size())
        offset += size
    return params
